### PR TITLE
Update to match current WHATWG

### PR DESCRIPTION
**Pull request by kemitchell**
This small PR:

1.  Updates the spec link in README, which is currently broken.

2.  Update the regular expression to match the current spec.

### CODE REVIEW

**Comment by jaydenseric** [comment]
It would be nice if this were merged sometime soon, otherwise I will have to publish an almost identical package.

**Comment by kemitchell** [comment]
@manuelstofer, can you be our hero? Thanks!

**Comment by kemitchell** [comment]
Thanks @njakob!

**Comment by njakob** [comment]
Thank you @kemitchell for your contribution! Sorry you had to wait so long to see it merged!

**Comment by kemitchell** [comment]
@njakob, no problem. Do you plan to release as 1.0.0?

**Comment by njakob** [comment]
@kemitchell This was actually released as v1.0.0 under [@smallpdf/is-email](https://www.npmjs.com/package/@smallpdf/is-email) !

**Pull request merged**
